version: '3'

services:
  moniteur:
    image: python:3.10.12
    container_name: moniteur
    working_dir: /moniteur
    ports:
      - 5000:5000
    volumes:
      - ./moniteur/app:/moniteur
      - ./processing:/processing
    networks:
      pipeline-net:
        ipv4_address: 172.20.0.10
    restart: on-failure:2
    command: sh -c "pip install --root-user-action=ignore --no-cache-dir -r requirements.txt && python app.py"
    
  downscaler:
    image: python:3.10.12
    container_name: downscaler
    working_dir: /downscaler 
    volumes:
      - ./downscaler/app:/downscaler
      - ./processing:/processing
    networks:
      - pipeline-net
    restart: on-failure:2
    depends_on:
      - moniteur
    command: sh -c "pip install --root-user-action=ignore --no-cache-dir -r requirements.txt && python app.py"
    
  
  langandsubtiles:
    image: python:3.10.12
    container_name: langandsubtiles
    working_dir: /langandsubtitle
    volumes:
      - ./langandsubtitle/app:/langandsubtitle
      - ./processing:/processing
    networks:
      - pipeline-net
    restart: on-failure:2
    depends_on:
      - moniteur
    command: sh -c "pip install --root-user-action=ignore --no-cache-dir -r requirements.txt && python app.py"
    

  animaldetect:
    image: python:3.10.12
    container_name: animaldetect
    working_dir: /animaldetect
    volumes:
      - ./animaldetect/app:/animaldetect
      - ./processing:/processing
    networks:
      - pipeline-net
    restart: on-failure:2
    depends_on:
      - moniteur
    command: sh -c "apt update && apt install -y libgl1 &&  pip install --root-user-action=ignore --no-cache-dir -r requirements.txt && python app.py"
    

networks:
  pipeline-net:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - gateway: 172.20.0.1
